spring.datasource.url=jdbc:postgresql://localhost:5432/gym
spring.datasource.username=guts
spring.datasource.password=Az90zz026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jwt.secret=z9MkAvGlxHN3Rw4sC9bv4DwzTo6oifEQqmQH2hCWc4s=
