spring.datasource.url=${STG_DB_URL}
spring.datasource.username=${STG_DB_USERNAME}
spring.datasource.password=${STG_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=when-authorized
